[project]
name = "hello-agent"
version = "0.1.0"
description = "LLM agent playground"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "litellm>=1.79.3",
  "openai>=2.7.2",
  "python-dotenv>=1.2.1",
  "ruff>=0.14.4",
]

[tool.uv]
python-preference = "managed"
prerelease = "allow"

[tool.uv.build-backend]
module-name = "ulib"

[tool.pyrefly]
project-includes = [
    "**/*.py",
    "**/*.ipynb",
]
